export const defaultAppData = {
  bookings: [],
  notifications: [],
  reviews: [
    {
      id: 'review-1',
      name: 'Kathi',
      rating: 5,
      provider: 'google',
      status: 'approved',
      createdAt: '2026-04-01',
      quote: 'Wir haben kurzlich einen sehr schonen Aufenthalt bei Watikolo genossen. Die ganze Umgebung war ruhig, sauber, und ideal fur einen entspannten Aufenthalt.',
    },
    {
      id: 'review-2',
      name: 'Miranda Scott',
      rating: 5,
      provider: 'google',
      status: 'approved',
      createdAt: '2026-03-21',
      quote: 'This is such a beautiful and incredible place to stay. The staff are all so amazing and welcoming, and the whole venue feels thoughtfully prepared for guests.',
    },
    {
      id: 'review-3',
      name: 'I1707KSbenc',
      rating: 5,
      provider: 'google',
      status: 'approved',
      createdAt: '2026-03-20',
      quote: 'Watikolo was one of the best places we have stayed, not just in the area, but among the places we would gladly recommend for a peaceful and memorable visit.',
    },
    {
      id: 'review-4',
      name: 'Ben Coleman',
      rating: 5,
      provider: 'google',
      status: 'approved',
      createdAt: '2026-03-19',
      quote: 'Watikolo was one of the best places we have stayed, not just in the usual sense of comfort, but in how easy and calm the whole experience felt from start to finish.',
    },
    {
      id: 'review-5',
      name: 'Sandra Du',
      rating: 5,
      provider: 'facebook',
      status: 'approved',
      createdAt: '2026-03-10',
      quote: 'I have nothing negative to say about our stay. Everything felt clean, organized, and welcoming, and the surroundings made the whole experience more relaxing.',
    },
    {
      id: 'review-6',
      name: 'BigBunster',
      rating: 5,
      provider: 'tripadvisor',
      status: 'approved',
      createdAt: '2026-02-27',
      quote: 'This is a hidden gem. The atmosphere feels restful, the property gives guests room to breathe, and the whole stay feels more special than a standard booking.',
    },
  ],
  venues: [
    {
      id: 'venue-1',
      name: 'The Grand Atrium',
      slug: 'the-grand-atrium',
      type: 'Ballroom',
      location: 'Tagum City, Davao del Norte',
      price: 85000,
      capacity: 280,
      rating: 4.9,
      shortDescription: 'A refined ballroom for elegant weddings, galas, and milestone celebrations.',
      description: 'The Grand Atrium pairs sweeping chandeliers with flexible floor planning, giving clients a premium setting for luxurious events without sacrificing convenience.',
      amenities: ['LED wall', 'Air-conditioned hall', 'VIP lounge', 'Bridal suite', 'Catering prep area'],
      eventTypes: ['Wedding', 'Debut', 'Birthday', 'Corporate'],
      heroImage: '/src/pictures/room1.jpg',
      gallery: ['/src/pictures/room2.jpg', '/src/pictures/room3.jpg', '/src/pictures/watikolo-home.png'],
      featured: true,
      availabilityText: '3 premium slots left this week',
      availability: 'Limited availability',
    },
    {
      id: 'venue-2',
      name: 'Lakeside Pavilion',
      slug: 'lakeside-pavilion',
      type: 'Garden',
      location: 'Panabo City, Davao del Norte',
      price: 62000,
      capacity: 180,
      rating: 4.8,
      shortDescription: 'An open-air venue framed by lush greenery and soft evening lights.',
      description: 'Lakeside Pavilion is built for intimate celebrations and romantic ceremonies, with a scenic garden aisle and flexible styling zones.',
      amenities: ['Garden aisle', 'Tent-ready lawn', 'Parking area', 'Sound-ready stage', 'Photo garden'],
      eventTypes: ['Wedding', 'Birthday', 'Debut', 'Other'],
      heroImage: '/src/pictures/w-pool.png',
      gallery: ['/src/pictures/nature.jpg', '/src/pictures/nature1.jpg', '/src/pictures/watikolo-lpool.png'],
      featured: true,
      availabilityText: 'Open for weekday reservations',
      availability: 'Open this week',
    },
    {
      id: 'venue-3',
      name: 'Skyline Terrace',
      slug: 'skyline-terrace',
      type: 'Rooftop',
      location: 'Davao City',
      price: 74000,
      capacity: 150,
      rating: 4.7,
      shortDescription: 'A rooftop venue with city lights, curated cocktails, and sunset-ready views.',
      description: 'Skyline Terrace is tailored for stylish evening functions, engagement parties, corporate mixers, and intimate receptions.',
      amenities: ['Sunset deck', 'Bar counter', 'Photo wall', 'Ambient lighting', 'Projector setup'],
      eventTypes: ['Corporate', 'Birthday', 'Wedding', 'Other'],
      heroImage: '/src/pictures/villa.png',
      gallery: ['/src/pictures/watikolo-main.png', '/src/pictures/outside1.png', '/src/pictures/outside2.png'],
      featured: true,
      availabilityText: 'Peak season demand',
      availability: 'Peak season',
    },
    {
      id: 'venue-4',
      name: 'Crestview Hall',
      slug: 'crestview-hall',
      type: 'Conference Hall',
      location: 'Tagum City, Davao del Norte',
      price: 54000,
      capacity: 220,
      rating: 4.6,
      shortDescription: 'A polished venue for forums, seminars, launches, and company gatherings.',
      description: 'Crestview Hall combines business-ready facilities with a warm guest experience, making it ideal for workshops and branded events.',
      amenities: ['Stage lighting', 'Built-in audio', 'Breakout room', 'Fiber internet', 'Registration foyer'],
      eventTypes: ['Corporate', 'Conference', 'Other'],
      heroImage: '/src/pictures/function.png',
      gallery: ['/src/pictures/function1.png', '/src/pictures/space.jpg', '/src/pictures/balcony.jpg'],
      availabilityText: 'Open for next week bookings',
      availability: 'Open this week',
    },
    {
      id: 'venue-5',
      name: 'Ivory Manor',
      slug: 'ivory-manor',
      type: 'Private Hall',
      location: 'Panabo City, Davao del Norte',
      price: 48000,
      capacity: 120,
      rating: 4.7,
      shortDescription: 'A boutique private hall designed for intimate milestones and curated gatherings.',
      description: 'Ivory Manor offers warm interiors, elegant table layouts, and a private atmosphere perfect for bespoke events and family celebrations.',
      amenities: ['Private ingress', 'Prep kitchen', 'Lounge corner', 'Stage riser', 'Ambient lighting'],
      eventTypes: ['Birthday', 'Debut', 'Wedding', 'Other'],
      heroImage: '/src/pictures/watikolo-home.png',
      gallery: ['/src/pictures/watikolo-2.png', '/src/pictures/outside.png', '/src/pictures/function.png'],
      availabilityText: 'Weekend slots filling up',
      availability: 'Limited availability',
    },
    {
      id: 'venue-6',
      name: 'Poolside Garden',
      slug: 'poolside-garden',
      type: 'Garden',
      location: 'Purok 4 Upper Puntod Road, Tabalong, Dauis, Bohol',
      price: 45000,
      capacity: 160,
      rating: 4.8,
      shortDescription: 'A relaxed poolside garden venue for birthdays, family gatherings, and intimate celebrations.',
      description: 'Poolside Garden gives guests a bright outdoor setting beside the pool, with flexible table layouts and easy access to the main house amenities.',
      amenities: ['Poolside setup', 'Garden tables', 'Parking area', 'Photo spots', 'Outdoor lounge'],
      eventTypes: ['Birthday', 'Debut', 'Wedding', 'Other'],
      heroImage: '/src/pictures/watikolo-lpool.png',
      gallery: ['/src/pictures/w-pool.png', '/src/pictures/nature.jpg', '/src/pictures/outside2.png'],
      featured: true,
      availabilityText: 'Available for daytime use',
      availability: 'Open this week',
    },
  ],
  packages: [
    { name: 'Essential', price: 5000, minGuests: 30, guestLabel: 'Good for 30 guests', isExclusive: false, inclusions: ['Basic styling support', 'Free use of billiard table', 'Free WiFi', 'Parking area', 'Pool access', 'Tables and chairs', 'Tables', 'Chairs'] },
    { name: 'Classic', price: 10000, minGuests: 30, guestLabel: 'Good for 30 guests', isExclusive: false, inclusions: ['Basic styling support', 'Free use of billiard table', 'Free use of videoke', 'Free WiFi', 'Parking area', 'Pool access', 'Tables and chairs', 'Tables', 'Chairs'] },
    { name: 'Premium', price: 15000, minGuests: 50, guestLabel: 'Good for 50 guests', isExclusive: true, inclusions: ['Basic styling support', 'Free use of billiard table', 'Free use of videoke', 'Free WiFi', 'Parking area', 'Pool access', 'Tables and chairs', 'Tables', 'Chairs'] },
    { name: 'Deluxe', price: 25000, minGuests: 100, guestLabel: 'Good for 100 guests', isExclusive: true, inclusions: ['3 room inclusions', 'Basic styling support', 'Free use of billiard table', 'Free use of videoke', 'Free use of whole house', 'Free WiFi', 'Kitchen use', 'Parking area', 'Pool access', 'Tables and chairs', 'Tables', 'Chairs'] },
    { name: 'Grand', price: 30000, minGuests: 100, guestLabel: 'Good for 100 guests / Exclusive use of the whole property / Good for 20 hours.', isExclusive: true, inclusions: ['3 room inclusions', 'Basic styling support', 'Free use of billiard table', 'Free use of videoke', 'Free use of whole house', 'Free WiFi', 'Kitchen use', 'Parking area', 'Pool access', 'Tables and chairs', 'Tables', 'Chairs'] },
    { name: 'Ultimate', price: 35000, minGuests: 150, guestLabel: 'Good for 150 guests / Exclusive use of the whole property / 22 hours.', isExclusive: true, inclusions: ['3 room inclusions', 'Basic styling support', 'Free use of billiard table', 'Free use of videoke', 'Free use of whole house', 'Free WiFi', 'Kitchen use', 'Parking area', 'Pool access', 'Tables and chairs', 'Tables', 'Chairs'] },
  ],
  rooms: [
    { id: 'room-1', name: 'Watikolo Luxe Stay', image: '/src/pictures/room1.jpg', capacity: 'Good for 2 Guests', price: 1999, inclusions: ['Air conditioning', 'Private bathroom', 'Smart TV', 'Free WiFi', 'Parking area'] },
    { id: 'room-2', name: 'Watikolo Grand Room', image: '/src/pictures/room2.jpg', capacity: 'Good for 3 Guests', price: 2499, inclusions: ['Air conditioning', 'Free WiFi', 'Cozy bed', 'Parking area'] },
    { id: 'room-big', name: 'Watikolo Family Room', image: '/src/pictures/room3.jpg', capacity: 'Good for 4 Guests', price: 3499, inclusions: ['Air conditioning', 'Private CR', 'Mini lounge', 'Free WiFi', 'Parking area'] },
  ],
  addOns: [
    { name: 'Decor Styling', price: 2500, description: 'Themed setup for the event area.' },
    { name: 'Sound System Upgrade', price: 1800, description: 'Enhanced speakers and audio support.' },
    { name: 'Projector & Screen', price: 1500, description: 'For AVP and presentations.' },
    { name: 'Welcome Drinks', price: 1200, description: 'Prepared refreshments for arriving guests.' },
  ],
  inventoryItems: [
    { id: 'inventory-beds', room_id: '', name: 'Beds', category: 'Room Amenities', itemType: 'reusable', totalQuantity: 6, availableQuantity: 6, inUseQuantity: 0, damagedQuantity: 0, unit: 'pcs', reorderLevel: 1, location: 'Shared / Rooms', notes: 'Combined room inventory. One unit is allocated per approved room booking.', updatedAt: '2026-04-01' },
    { id: 'inventory-pillows', room_id: '', name: 'Pillows', category: 'Room Amenities', itemType: 'reusable', totalQuantity: 18, availableQuantity: 18, inUseQuantity: 0, damagedQuantity: 0, unit: 'pcs', reorderLevel: 2, location: 'Shared / Rooms', notes: 'Combined room inventory. One unit is allocated per approved room booking.', updatedAt: '2026-04-01' },
    { id: 'inventory-towels', room_id: '', name: 'Towels', category: 'Housekeeping', itemType: 'reusable', totalQuantity: 18, availableQuantity: 18, inUseQuantity: 0, damagedQuantity: 0, unit: 'pcs', reorderLevel: 2, location: 'Shared / Rooms', notes: 'Combined room inventory. One unit is allocated per approved room booking.', updatedAt: '2026-04-01' },
    { id: 'inventory-tv', room_id: '', name: 'TV', category: 'Appliance', itemType: 'reusable', totalQuantity: 3, availableQuantity: 3, inUseQuantity: 0, damagedQuantity: 0, unit: 'unit', reorderLevel: 1, location: 'Shared / Rooms', notes: 'Combined room inventory. One unit is allocated per approved room booking.', updatedAt: '2026-04-01' },
    { id: 'inventory-air-conditioner', room_id: '', name: 'Air Conditioner', category: 'Appliance', itemType: 'reusable', totalQuantity: 3, availableQuantity: 3, inUseQuantity: 0, damagedQuantity: 0, unit: 'unit', reorderLevel: 1, location: 'Shared / Rooms', notes: 'Combined room inventory. One unit is allocated per approved room booking.', updatedAt: '2026-04-01' },
  ],
  inventoryTransactions: [],
};
